spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giuct?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysql1234
  jpa:
    generate-ddl: true
    show-sql: true
    #hibernate:ddl-auto: update
  main:
    banner-mode: off
logging:
  level:
    root: ERROR


